"""create_document_groups_answers_and_warnings

Revision ID: 1622bac42c58
Revises: fe84d40b3f6a
Create Date: 2026-09-19 20:34:21.330928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1622bac42c58'
down_revision: Union[str, Sequence[str], None] = 'fe84d40b3f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_groups_id'), 'document_groups', ['id'], unique=False)
    op.create_index(op.f('ix_document_groups_owner_user_id'), 'document_groups', ['owner_user_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_confidence', sa.Float(), nullable=False),
    sa.Column('answer_match_method', sa.String(length=30), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=True)
    op.create_index(op.f('ix_answers_source_document_id'), 'answers', ['source_document_id'], unique=False)
    op.create_table('processing_warnings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('warning_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_warnings_document_id'), 'processing_warnings', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_warnings_id'), 'processing_warnings', ['id'], unique=False)
    op.create_index(op.f('ix_processing_warnings_question_id'), 'processing_warnings', ['question_id'], unique=False)
    op.create_foreign_key('fk_documents_group_id', 'documents', 'document_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_group_id', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_processing_warnings_question_id'), table_name='processing_warnings')
    op.drop_index(op.f('ix_processing_warnings_id'), table_name='processing_warnings')
    op.drop_index(op.f('ix_processing_warnings_document_id'), table_name='processing_warnings')
    op.drop_table('processing_warnings')
    op.drop_index(op.f('ix_answers_source_document_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_document_groups_owner_user_id'), table_name='document_groups')
    op.drop_index(op.f('ix_document_groups_id'), table_name='document_groups')
    op.drop_table('document_groups')
    # ### end Alembic commands ###
